### ISSUE TITLE
Possibility for single image zero-shot depth estimation

### ISSUE THREAD

**Issue by plusgrey** [RuijieZhu94/mmdepth#3]
Hi, ruijie

Your work is amazing. I wonder if it is possible to implement your model for a single image depth estimation rather than test it on datasets using the tool/test.py?

Thanks for your help in advance.

**Comment by RuijieZhu94** [comment]
Hi @plusgrey , sorry for the late reply. Great suggestion! I just uploaded a [sample code](https://github.com/RuijieZhu94/mmdepth/blob/main/tools/inference.py) and you can implement it with simple code modification.

**Comment by RuijieZhu94** [comment]
![image](https://github.com/user-attachments/assets/1b8527c5-6b66-43fb-8924-9dd6466609c3)
If it works well, your screen should show a picture like this.

**Comment by plusgrey** [comment]
Hi Ruijie,

Thanks for your help and prompt response. It does helped a lot.

**Comment by plusgrey** [comment]
Hi @RuijieZhu94, I encountered an error when calling the list_models methods.
![image](https://github.com/user-attachments/assets/1ae6a3de-db2f-4dc1-90f5-493db36e58b9)
Do you have any idea?

**Comment by plusgrey** [comment]
I manually added 'mmdepth' to the mmengine's config. Then the new error shows:


08/08 14:51:36 - mmengine - INFO - model_name: scaledepth_clip_NYU_KITTI_352x512
model_name: scaledepth_clip_NYU_KITTI_352x512
model_name: s
model_name: c
model_name: a
model_name: l
model_name: e
model_name: d
model_name: e
model_name: p
model_name: t
model_name: h

Loads checkpoint by local backend from path: /home/user/Desktop/mmdepth/checkpoints/iter_40000.pth
INFO:root:Loaded convnext_large_d_320 model config.
INFO:root:Loading pretrained convnext_large_d_320 weights (laion2b_s29b_b131k_ft_soup).
Traceback (most recent call last):
  File "inference.py", line 5, in <module>
    inferencer = MMSegInferencer(model='scaledepth_clip_NYU_KITTI_352x512',weights='/home/user/Desktop/mmdepth/checkpoints/iter_40000.pth')
  File "/home/user/Desktop/mmdepth/mmdepth/apis/mmseg_inferencer.py", line 81, in __init__
    super().__init__(
  File "/home/user/anaconda3/envs/mmdepth/lib/python3.8/site-packages/mmengine/infer/infer.py", line 180, in __init__
    self.model = self._init_model(cfg, weights, device)  # type: ignore
  File "/home/user/anaconda3/envs/mmdepth/lib/python3.8/site-packages/mmengine/infer/infer.py", line 483, in _init_model
    model = MODELS.build(cfg.model)
  File "/home/user/anaconda3/envs/mmdepth/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/user/anaconda3/envs/mmdepth/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/user/anaconda3/envs/mmdepth/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/user/Desktop/mmdepth/mmdepth/models/segmentors/depth_estimator.py", line 87, in __init__
    super().__init__(
  File "/home/user/Desktop/mmdepth/mmdepth/models/segmentors/encoder_decoder.py", line 92, in __init__
    self._init_decode_head(decode_head)
  File "/home/user/Desktop/mmdepth/mmdepth/models/segmentors/encoder_decoder.py", line 102, in _init_decode_head
    self.decode_head = MODELS.build(decode_head)
  File "/home/user/anaconda3/envs/mmdepth/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/user/anaconda3/envs/mmdepth/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/user/anaconda3/envs/mmdepth/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/user/Desktop/mmdepth/projects/ScaleDepth/decode_head/scaledepth_head.py", line 73, in __init__
    super().__init__(num_queries=num_queries + num_cls_query, **kwargs)
  File "/home/user/anaconda3/envs/mmdepth/lib/python3.8/site-packages/mmdet/models/dense_heads/mask2former_head.py", line 153, in __init__
    self.class_weight = loss_cls.class_weight
AttributeError: 'dict' object has no attribute 'class_weight'

**Comment by RuijieZhu94** [comment]
This seems to be a minor bug in mmsegmentation. You just need to change loss_cls.class_weight to loss_cls["class_weight"].

**Comment by RuijieZhu94** [comment]
Closing this issue. If there are any other questions please open another issue.
