### ISSUE TITLE
Error in Inference demo

### ISSUE THREAD

**Issue by chycxyzd** [RuijieZhu94/mmdepth#4]
This seems to be an error caused by a network problem, but my internet link is OK for sure, do you have any insight? Here is the error message.

`10/30 15:00:07 - mmengine - INFO - model_name: scaledepth_clip_NYU_KITTI_352x512
model_name: scaledepth_clip_NYU_KITTI_352x512
model_name: s
model_name: c
model_name: a
model_name: l
model_name: e
model_name: d
model_name: e
model_name: p
model_name: t
model_name: h

Loads checkpoint by local backend from path: work_dirs/scaledepth_clip_NYU_KITTI_352x512/iter_40000.pth
Traceback (most recent call last):
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\urllib3\connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\urllib3\connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000026D38A4FAC0>, 'Connection to huggingface.co timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\urllib3\connectionpool.py", line 802, in urlopen
    retries = retries.increment(
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\urllib3\util\retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup/resolve/main/open_clip_pytorch_model.bin (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026D38A4FAC0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\huggingface_hub\file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\huggingface_hub\file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\huggingface_hub\file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\huggingface_hub\file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\huggingface_hub\utils\_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup/resolve/main/open_clip_pytorch_model.bin (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026D38A4FAC0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: c10ef4a7-d886-4979-b3bc-d9d6f6dc4ed8)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\open_clip\pretrained.py", line 747, in download_pretrained_from_hf
    cached_file = hf_hub_download(
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\huggingface_hub\file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\huggingface_hub\file_download.py", line 1487, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\plant_predict\mmdepth-main\tools\inference.py", line 5, in <module>
    inferencer = MMSegInferencer(model='scaledepth_clip_NYU_KITTI_352x512')
  File "D:\plant_predict\mmdepth-main\mmdepth\apis\mmseg_inferencer.py", line 81, in __init__
    super().__init__(
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\infer\infer.py", line 180, in __init__
    self.model = self._init_model(cfg, weights, device)  # type: ignore
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\infer\infer.py", line 483, in _init_model
    model = MODELS.build(cfg.model)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "D:\plant_predict\mmdepth-main\mmdepth\models\segmentors\depth_estimator.py", line 87, in __init__
    super().__init__(
  File "D:\plant_predict\mmdepth-main\mmdepth\models\segmentors\encoder_decoder.py", line 89, in __init__
    self.backbone = MODELS.build(backbone)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "D:\plant_predict\mmdepth-main\projects\ScaleDepth\backbone\clip.py", line 47, in __init__
    self.clip_model, _, clip_preprocess = open_clip.create_model_and_transforms(clip_model_name, pretrained=clip_model_pretrain)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\open_clip\factory.py", line 484, in create_model_and_transforms
    model = create_model(
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\open_clip\factory.py", line 367, in create_model
    checkpoint_path = download_pretrained(pretrained_cfg, cache_dir=cache_dir)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\open_clip\pretrained.py", line 785, in download_pretrained
    target = download_pretrained_from_hf(model_id, cache_dir=cache_dir)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\open_clip\pretrained.py", line 755, in download_pretrained_from_hf
    raise FileNotFoundError(f"Failed to download file ({filename}) for {model_id}. Last error: {e}")
FileNotFoundError: Failed to download file (open_clip_pytorch_model.bin) for laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup. Last error: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
`

Maybe the hugging face link is not working? If so, is there any other way to get the demo running?

**Comment by RuijieZhu94** [comment]
I seem to have encountered a similar problem before. It seems to be caused by an unstable proxy connection. It is recommended to try downloading it locally and then importing it directly.

**Comment by chycxyzd** [comment]
Thank you for your prompt reply. I followed your advice and downloaded the model file (https://huggingface.co/laion/CLIP-convnext_large_d_320.laion2B-s29B-b131K-ft-soup) to import directly locally. However, the following issues occurred:

`Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 116, in main
    runner = Runner.from_cfg(cfg)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\runner\runner.py", line 462, in from_cfg
    runner = cls(
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\runner\runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\runner\runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "D:\plant_predict\mmdepth-main\mmdepth\models\segmentors\depth_estimator.py", line 87, in __init__
    super().__init__(
  File "D:\plant_predict\mmdepth-main\mmdepth\models\segmentors\encoder_decoder.py", line 92, in __init__
    self._init_decode_head(decode_head)
  File "D:\plant_predict\mmdepth-main\mmdepth\models\segmentors\encoder_decoder.py", line 102, in _init_decode_head
    self.decode_head = MODELS.build(decode_head)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "D:\plant_predict\mmdepth-main\projects\ScaleDepth\decode_head\scaledepth_head.py", line 73, in __init__
    super().__init__(num_queries=num_queries + num_cls_query, **kwargs)
  File "D:\anaconda3\envs\mmdepth\lib\site-packages\mmdet\models\dense_heads\mask2former_head.py", line 153, in __init__
    self.class_weight = loss_cls.class_weight
AttributeError: 'dict' object has no attribute 'class_weight'
`
Do you have any good solutions?

**Comment by RuijieZhu94** [comment]
See https://github.com/RuijieZhu94/mmdepth/issues/3#issuecomment-2275987068

**Comment by chycxyzd** [comment]
Thank you for your guidance. My issue has been resolved and I will close it.
